//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.3053 版自动生成。
// 
#pragma warning disable 1591

namespace SmsTerrace.SmsWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSmsResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSmsStateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUpSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendWithSubOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBufferWithSubOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendToBufferOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitMMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetPasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::SmsTerrace.Properties.Settings.Default.SmsTerrace_SmsWebService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBalanceCompletedEventHandler GetBalanceCompleted;
        
        /// <remarks/>
        public event GetSmsResultCompletedEventHandler GetSmsResultCompleted;
        
        /// <remarks/>
        public event GetSmsStateCompletedEventHandler GetSmsStateCompleted;
        
        /// <remarks/>
        public event GetReportCompletedEventHandler GetReportCompleted;
        
        /// <remarks/>
        public event GetUpSmsCompletedEventHandler GetUpSmsCompleted;
        
        /// <remarks/>
        public event SendCompletedEventHandler SendCompleted;
        
        /// <remarks/>
        public event SendWithSubCompletedEventHandler SendWithSubCompleted;
        
        /// <remarks/>
        public event SendBufferWithSubCompletedEventHandler SendBufferWithSubCompleted;
        
        /// <remarks/>
        public event SendToBufferCompletedEventHandler SendToBufferCompleted;
        
        /// <remarks/>
        public event SubmitMMSCompletedEventHandler SubmitMMSCompleted;
        
        /// <remarks/>
        public event SetPasswordCompletedEventHandler SetPasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBalance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetBalanceResp GetBalance(string UserID, string Password, string BusinessId) {
            object[] results = this.Invoke("GetBalance", new object[] {
                        UserID,
                        Password,
                        BusinessId});
            return ((GetBalanceResp)(results[0]));
        }
        
        /// <remarks/>
        public void GetBalanceAsync(string UserID, string Password, string BusinessId) {
            this.GetBalanceAsync(UserID, Password, BusinessId, null);
        }
        
        /// <remarks/>
        public void GetBalanceAsync(string UserID, string Password, string BusinessId, object userState) {
            if ((this.GetBalanceOperationCompleted == null)) {
                this.GetBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBalanceOperationCompleted);
            }
            this.InvokeAsync("GetBalance", new object[] {
                        UserID,
                        Password,
                        BusinessId}, this.GetBalanceOperationCompleted, userState);
        }
        
        private void OnGetBalanceOperationCompleted(object arg) {
            if ((this.GetBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBalanceCompleted(this, new GetBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSmsResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetSmsResultResp GetSmsResult(string UserID, string Password, string SubmitID) {
            object[] results = this.Invoke("GetSmsResult", new object[] {
                        UserID,
                        Password,
                        SubmitID});
            return ((GetSmsResultResp)(results[0]));
        }
        
        /// <remarks/>
        public void GetSmsResultAsync(string UserID, string Password, string SubmitID) {
            this.GetSmsResultAsync(UserID, Password, SubmitID, null);
        }
        
        /// <remarks/>
        public void GetSmsResultAsync(string UserID, string Password, string SubmitID, object userState) {
            if ((this.GetSmsResultOperationCompleted == null)) {
                this.GetSmsResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSmsResultOperationCompleted);
            }
            this.InvokeAsync("GetSmsResult", new object[] {
                        UserID,
                        Password,
                        SubmitID}, this.GetSmsResultOperationCompleted, userState);
        }
        
        private void OnGetSmsResultOperationCompleted(object arg) {
            if ((this.GetSmsResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSmsResultCompleted(this, new GetSmsResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSmsState", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetSmsStateResp GetSmsState(string UserID, string Password, string Rows) {
            object[] results = this.Invoke("GetSmsState", new object[] {
                        UserID,
                        Password,
                        Rows});
            return ((GetSmsStateResp)(results[0]));
        }
        
        /// <remarks/>
        public void GetSmsStateAsync(string UserID, string Password, string Rows) {
            this.GetSmsStateAsync(UserID, Password, Rows, null);
        }
        
        /// <remarks/>
        public void GetSmsStateAsync(string UserID, string Password, string Rows, object userState) {
            if ((this.GetSmsStateOperationCompleted == null)) {
                this.GetSmsStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSmsStateOperationCompleted);
            }
            this.InvokeAsync("GetSmsState", new object[] {
                        UserID,
                        Password,
                        Rows}, this.GetSmsStateOperationCompleted, userState);
        }
        
        private void OnGetSmsStateOperationCompleted(object arg) {
            if ((this.GetSmsStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSmsStateCompleted(this, new GetSmsStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetSmsStateResp GetReport(string uid, string pwd, string msgId, string phoneNum) {
            object[] results = this.Invoke("GetReport", new object[] {
                        uid,
                        pwd,
                        msgId,
                        phoneNum});
            return ((GetSmsStateResp)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportAsync(string uid, string pwd, string msgId, string phoneNum) {
            this.GetReportAsync(uid, pwd, msgId, phoneNum, null);
        }
        
        /// <remarks/>
        public void GetReportAsync(string uid, string pwd, string msgId, string phoneNum, object userState) {
            if ((this.GetReportOperationCompleted == null)) {
                this.GetReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportOperationCompleted);
            }
            this.InvokeAsync("GetReport", new object[] {
                        uid,
                        pwd,
                        msgId,
                        phoneNum}, this.GetReportOperationCompleted, userState);
        }
        
        private void OnGetReportOperationCompleted(object arg) {
            if ((this.GetReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportCompleted(this, new GetReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUpSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetUpSmsResp GetUpSms(string UserID, string Password, string Rows) {
            object[] results = this.Invoke("GetUpSms", new object[] {
                        UserID,
                        Password,
                        Rows});
            return ((GetUpSmsResp)(results[0]));
        }
        
        /// <remarks/>
        public void GetUpSmsAsync(string UserID, string Password, string Rows) {
            this.GetUpSmsAsync(UserID, Password, Rows, null);
        }
        
        /// <remarks/>
        public void GetUpSmsAsync(string UserID, string Password, string Rows, object userState) {
            if ((this.GetUpSmsOperationCompleted == null)) {
                this.GetUpSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUpSmsOperationCompleted);
            }
            this.InvokeAsync("GetUpSms", new object[] {
                        UserID,
                        Password,
                        Rows}, this.GetUpSmsOperationCompleted, userState);
        }
        
        private void OnGetUpSmsOperationCompleted(object arg) {
            if ((this.GetUpSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUpSmsCompleted(this, new GetUpSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResp Send(string UserID, string Password, string BusinessId, string MsgContent, string Mobiles, string SendTime) {
            object[] results = this.Invoke("Send", new object[] {
                        UserID,
                        Password,
                        BusinessId,
                        MsgContent,
                        Mobiles,
                        SendTime});
            return ((SendResp)(results[0]));
        }
        
        /// <remarks/>
        public void SendAsync(string UserID, string Password, string BusinessId, string MsgContent, string Mobiles, string SendTime) {
            this.SendAsync(UserID, Password, BusinessId, MsgContent, Mobiles, SendTime, null);
        }
        
        /// <remarks/>
        public void SendAsync(string UserID, string Password, string BusinessId, string MsgContent, string Mobiles, string SendTime, object userState) {
            if ((this.SendOperationCompleted == null)) {
                this.SendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOperationCompleted);
            }
            this.InvokeAsync("Send", new object[] {
                        UserID,
                        Password,
                        BusinessId,
                        MsgContent,
                        Mobiles,
                        SendTime}, this.SendOperationCompleted, userState);
        }
        
        private void OnSendOperationCompleted(object arg) {
            if ((this.SendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendCompleted(this, new SendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendWithSub", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResp SendWithSub(string UserID, string Password, string BusinessId, string MsgContent, string Mobiles, string SendTime, string SourceId) {
            object[] results = this.Invoke("SendWithSub", new object[] {
                        UserID,
                        Password,
                        BusinessId,
                        MsgContent,
                        Mobiles,
                        SendTime,
                        SourceId});
            return ((SendResp)(results[0]));
        }
        
        /// <remarks/>
        public void SendWithSubAsync(string UserID, string Password, string BusinessId, string MsgContent, string Mobiles, string SendTime, string SourceId) {
            this.SendWithSubAsync(UserID, Password, BusinessId, MsgContent, Mobiles, SendTime, SourceId, null);
        }
        
        /// <remarks/>
        public void SendWithSubAsync(string UserID, string Password, string BusinessId, string MsgContent, string Mobiles, string SendTime, string SourceId, object userState) {
            if ((this.SendWithSubOperationCompleted == null)) {
                this.SendWithSubOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendWithSubOperationCompleted);
            }
            this.InvokeAsync("SendWithSub", new object[] {
                        UserID,
                        Password,
                        BusinessId,
                        MsgContent,
                        Mobiles,
                        SendTime,
                        SourceId}, this.SendWithSubOperationCompleted, userState);
        }
        
        private void OnSendWithSubOperationCompleted(object arg) {
            if ((this.SendWithSubCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendWithSubCompleted(this, new SendWithSubCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendBufferWithSub", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResp SendBufferWithSub(string UserID, string Password, string BusinessId, string MsgContent, string Mobiles, string SendTime, string SourceId) {
            object[] results = this.Invoke("SendBufferWithSub", new object[] {
                        UserID,
                        Password,
                        BusinessId,
                        MsgContent,
                        Mobiles,
                        SendTime,
                        SourceId});
            return ((SendResp)(results[0]));
        }
        
        /// <remarks/>
        public void SendBufferWithSubAsync(string UserID, string Password, string BusinessId, string MsgContent, string Mobiles, string SendTime, string SourceId) {
            this.SendBufferWithSubAsync(UserID, Password, BusinessId, MsgContent, Mobiles, SendTime, SourceId, null);
        }
        
        /// <remarks/>
        public void SendBufferWithSubAsync(string UserID, string Password, string BusinessId, string MsgContent, string Mobiles, string SendTime, string SourceId, object userState) {
            if ((this.SendBufferWithSubOperationCompleted == null)) {
                this.SendBufferWithSubOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBufferWithSubOperationCompleted);
            }
            this.InvokeAsync("SendBufferWithSub", new object[] {
                        UserID,
                        Password,
                        BusinessId,
                        MsgContent,
                        Mobiles,
                        SendTime,
                        SourceId}, this.SendBufferWithSubOperationCompleted, userState);
        }
        
        private void OnSendBufferWithSubOperationCompleted(object arg) {
            if ((this.SendBufferWithSubCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBufferWithSubCompleted(this, new SendBufferWithSubCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendToBuffer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResp SendToBuffer(string UserID, string Password, string BusinessId, string MsgContent, string Mobiles, string SendTime, string SourceId, string bufferParam) {
            object[] results = this.Invoke("SendToBuffer", new object[] {
                        UserID,
                        Password,
                        BusinessId,
                        MsgContent,
                        Mobiles,
                        SendTime,
                        SourceId,
                        bufferParam});
            return ((SendResp)(results[0]));
        }
        
        /// <remarks/>
        public void SendToBufferAsync(string UserID, string Password, string BusinessId, string MsgContent, string Mobiles, string SendTime, string SourceId, string bufferParam) {
            this.SendToBufferAsync(UserID, Password, BusinessId, MsgContent, Mobiles, SendTime, SourceId, bufferParam, null);
        }
        
        /// <remarks/>
        public void SendToBufferAsync(string UserID, string Password, string BusinessId, string MsgContent, string Mobiles, string SendTime, string SourceId, string bufferParam, object userState) {
            if ((this.SendToBufferOperationCompleted == null)) {
                this.SendToBufferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendToBufferOperationCompleted);
            }
            this.InvokeAsync("SendToBuffer", new object[] {
                        UserID,
                        Password,
                        BusinessId,
                        MsgContent,
                        Mobiles,
                        SendTime,
                        SourceId,
                        bufferParam}, this.SendToBufferOperationCompleted, userState);
        }
        
        private void OnSendToBufferOperationCompleted(object arg) {
            if ((this.SendToBufferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendToBufferCompleted(this, new SendToBufferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubmitMMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResp SubmitMMS(string UserID, string Password, string BusinessId, string Mobiles, string SendTime, string SourceId, MMS Mms) {
            object[] results = this.Invoke("SubmitMMS", new object[] {
                        UserID,
                        Password,
                        BusinessId,
                        Mobiles,
                        SendTime,
                        SourceId,
                        Mms});
            return ((SendResp)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitMMSAsync(string UserID, string Password, string BusinessId, string Mobiles, string SendTime, string SourceId, MMS Mms) {
            this.SubmitMMSAsync(UserID, Password, BusinessId, Mobiles, SendTime, SourceId, Mms, null);
        }
        
        /// <remarks/>
        public void SubmitMMSAsync(string UserID, string Password, string BusinessId, string Mobiles, string SendTime, string SourceId, MMS Mms, object userState) {
            if ((this.SubmitMMSOperationCompleted == null)) {
                this.SubmitMMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitMMSOperationCompleted);
            }
            this.InvokeAsync("SubmitMMS", new object[] {
                        UserID,
                        Password,
                        BusinessId,
                        Mobiles,
                        SendTime,
                        SourceId,
                        Mms}, this.SubmitMMSOperationCompleted, userState);
        }
        
        private void OnSubmitMMSOperationCompleted(object arg) {
            if ((this.SubmitMMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitMMSCompleted(this, new SubmitMMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetPasswordResp SetPassword(string UserID, string Password, string NewPassword) {
            object[] results = this.Invoke("SetPassword", new object[] {
                        UserID,
                        Password,
                        NewPassword});
            return ((SetPasswordResp)(results[0]));
        }
        
        /// <remarks/>
        public void SetPasswordAsync(string UserID, string Password, string NewPassword) {
            this.SetPasswordAsync(UserID, Password, NewPassword, null);
        }
        
        /// <remarks/>
        public void SetPasswordAsync(string UserID, string Password, string NewPassword, object userState) {
            if ((this.SetPasswordOperationCompleted == null)) {
                this.SetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPasswordOperationCompleted);
            }
            this.InvokeAsync("SetPassword", new object[] {
                        UserID,
                        Password,
                        NewPassword}, this.SetPasswordOperationCompleted, userState);
        }
        
        private void OnSetPasswordOperationCompleted(object arg) {
            if ((this.SetPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPasswordCompleted(this, new SetPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceResp {
        
        private int balanceField;
        
        private ErrorCode errorDescField;
        
        private int resultField;
        
        /// <remarks/>
        public int Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public ErrorCode ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ErrorCode {
        
        /// <remarks/>
        BALANCE_ERROR,
        
        /// <remarks/>
        BID_ERROR,
        
        /// <remarks/>
        CALLER_ERROR,
        
        /// <remarks/>
        MSG_LENGTH_ERROR,
        
        /// <remarks/>
        MSG_TYPE_ERROR,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        SEND_TIME_ERROR,
        
        /// <remarks/>
        SOURCE_ID_ERROR,
        
        /// <remarks/>
        SOURCE_ID_LENGTH_ERROR,
        
        /// <remarks/>
        SYSTEM_ERROR,
        
        /// <remarks/>
        USER_ID_OR_PWD_ERROR,
        
        /// <remarks/>
        PARAM_ERROR,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SetPasswordResp {
        
        private ErrorCode errorDescField;
        
        private int resultField;
        
        /// <remarks/>
        public ErrorCode ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Multimedia {
        
        private string nameField;
        
        private byte[] valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MMSFrame {
        
        private Multimedia[] mediaListField;
        
        private string signField;
        
        private string descField;
        
        /// <remarks/>
        public Multimedia[] MediaList {
            get {
                return this.mediaListField;
            }
            set {
                this.mediaListField = value;
            }
        }
        
        /// <remarks/>
        public string Sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
            }
        }
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MMS {
        
        private string titleField;
        
        private string signField;
        
        private string descField;
        
        private MMSFrame[] frameListField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
            }
        }
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public MMSFrame[] FrameList {
            get {
                return this.frameListField;
            }
            set {
                this.frameListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SendResp {
        
        private string respDescField;
        
        private string blackMobilesField;
        
        private ErrorCode errorDescField;
        
        private string errorMobilesField;
        
        private int resultField;
        
        private string submitIDField;
        
        /// <remarks/>
        public string RespDesc {
            get {
                return this.respDescField;
            }
            set {
                this.respDescField = value;
            }
        }
        
        /// <remarks/>
        public string BlackMobiles {
            get {
                return this.blackMobilesField;
            }
            set {
                this.blackMobilesField = value;
            }
        }
        
        /// <remarks/>
        public ErrorCode ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMobiles {
            get {
                return this.errorMobilesField;
            }
            set {
                this.errorMobilesField = value;
            }
        }
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitID {
            get {
                return this.submitIDField;
            }
            set {
                this.submitIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UpSms {
        
        private string msgContentField;
        
        private string srcTerminalIDField;
        
        private string subNumberField;
        
        private string upTimeField;
        
        /// <remarks/>
        public string MsgContent {
            get {
                return this.msgContentField;
            }
            set {
                this.msgContentField = value;
            }
        }
        
        /// <remarks/>
        public string SrcTerminalID {
            get {
                return this.srcTerminalIDField;
            }
            set {
                this.srcTerminalIDField = value;
            }
        }
        
        /// <remarks/>
        public string SubNumber {
            get {
                return this.subNumberField;
            }
            set {
                this.subNumberField = value;
            }
        }
        
        /// <remarks/>
        public string UpTime {
            get {
                return this.upTimeField;
            }
            set {
                this.upTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUpSmsResp {
        
        private int countField;
        
        private ErrorCode errorDescField;
        
        private int resultField;
        
        private UpSms[] smsField;
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public ErrorCode ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public UpSms[] Sms {
            get {
                return this.smsField;
            }
            set {
                this.smsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SmsRpt {
        
        private string destTerminalIDField;
        
        private string msgIDField;
        
        private string statusField;
        
        /// <remarks/>
        public string DestTerminalID {
            get {
                return this.destTerminalIDField;
            }
            set {
                this.destTerminalIDField = value;
            }
        }
        
        /// <remarks/>
        public string MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsStateResp {
        
        private ErrorCode errorDescField;
        
        private int resultField;
        
        private SmsRpt[] smsField;
        
        /// <remarks/>
        public ErrorCode ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public SmsRpt[] Sms {
            get {
                return this.smsField;
            }
            set {
                this.smsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsResultResp {
        
        private ErrorCode errorDescField;
        
        private int failureCountField;
        
        private int presendCountField;
        
        private int resultField;
        
        private string submitIDField;
        
        private int successCountField;
        
        /// <remarks/>
        public ErrorCode ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public int FailureCount {
            get {
                return this.failureCountField;
            }
            set {
                this.failureCountField = value;
            }
        }
        
        /// <remarks/>
        public int PresendCount {
            get {
                return this.presendCountField;
            }
            set {
                this.presendCountField = value;
            }
        }
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitID {
            get {
                return this.submitIDField;
            }
            set {
                this.submitIDField = value;
            }
        }
        
        /// <remarks/>
        public int SuccessCount {
            get {
                return this.successCountField;
            }
            set {
                this.successCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetBalanceCompletedEventHandler(object sender, GetBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetBalanceResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetBalanceResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetSmsResultCompletedEventHandler(object sender, GetSmsResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSmsResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSmsResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetSmsResultResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetSmsResultResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetSmsStateCompletedEventHandler(object sender, GetSmsStateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSmsStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSmsStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetSmsStateResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetSmsStateResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetReportCompletedEventHandler(object sender, GetReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetSmsStateResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetSmsStateResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetUpSmsCompletedEventHandler(object sender, GetUpSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUpSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUpSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUpSmsResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUpSmsResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SendCompletedEventHandler(object sender, SendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SendWithSubCompletedEventHandler(object sender, SendWithSubCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendWithSubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendWithSubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SendBufferWithSubCompletedEventHandler(object sender, SendBufferWithSubCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBufferWithSubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBufferWithSubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SendToBufferCompletedEventHandler(object sender, SendToBufferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendToBufferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendToBufferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SubmitMMSCompletedEventHandler(object sender, SubmitMMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitMMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitMMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SetPasswordCompletedEventHandler(object sender, SetPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetPasswordResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetPasswordResp)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591