//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.3053 版自动生成。
// 
#pragma warning disable 1591

namespace SmsTerrace.ClientWebServer {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClientServerSoap", Namespace="http://HzTerrace.org/")]
    public partial class ClientServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MmsToServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ClientServer() {
            this.Url = global::SmsTerrace.Properties.Settings.Default.SmsTerrace_ClientWebServer_ClientServer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MmsToServiceCompletedEventHandler MmsToServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://HzTerrace.org/MmsToService", RequestNamespace="http://HzTerrace.org/", ResponseNamespace="http://HzTerrace.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OpRespOfSendResp MmsToService(string[] paramList) {
            object[] results = this.Invoke("MmsToService", new object[] {
                        paramList});
            return ((OpRespOfSendResp)(results[0]));
        }
        
        /// <remarks/>
        public void MmsToServiceAsync(string[] paramList) {
            this.MmsToServiceAsync(paramList, null);
        }
        
        /// <remarks/>
        public void MmsToServiceAsync(string[] paramList, object userState) {
            if ((this.MmsToServiceOperationCompleted == null)) {
                this.MmsToServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMmsToServiceOperationCompleted);
            }
            this.InvokeAsync("MmsToService", new object[] {
                        paramList}, this.MmsToServiceOperationCompleted, userState);
        }
        
        private void OnMmsToServiceOperationCompleted(object arg) {
            if ((this.MmsToServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MmsToServiceCompleted(this, new MmsToServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://HzTerrace.org/")]
    public partial class OpRespOfSendResp {
        
        private OpResp stateField;
        
        private SendResp returnResultField;
        
        /// <remarks/>
        public OpResp State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public SendResp ReturnResult {
            get {
                return this.returnResultField;
            }
            set {
                this.returnResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://HzTerrace.org/")]
    public partial class OpResp {
        
        private RespCode respField;
        
        private int resultField;
        
        private string respDescField;
        
        /// <remarks/>
        public RespCode Resp {
            get {
                return this.respField;
            }
            set {
                this.respField = value;
            }
        }
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string RespDesc {
            get {
                return this.respDescField;
            }
            set {
                this.respDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://HzTerrace.org/")]
    public enum RespCode {
        
        /// <remarks/>
        OTHER,
        
        /// <remarks/>
        PRO,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        ERROR_PARAM,
        
        /// <remarks/>
        ERROR_SEND_TIME,
        
        /// <remarks/>
        ERROR_CALLER,
        
        /// <remarks/>
        ERROR_USER_ID_OR_PWD,
        
        /// <remarks/>
        ERROR_BID,
        
        /// <remarks/>
        ERROR_BALANCE,
        
        /// <remarks/>
        ERROR_IP,
        
        /// <remarks/>
        ERROR_SYSTEM,
        
        /// <remarks/>
        ERROR_OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://HzTerrace.org/")]
    public partial class SendResp {
        
        private string respDescField;
        
        private string blackMobilesField;
        
        private ErrorCode errorDescField;
        
        private string errorMobilesField;
        
        private int resultField;
        
        private string submitIDField;
        
        /// <remarks/>
        public string RespDesc {
            get {
                return this.respDescField;
            }
            set {
                this.respDescField = value;
            }
        }
        
        /// <remarks/>
        public string BlackMobiles {
            get {
                return this.blackMobilesField;
            }
            set {
                this.blackMobilesField = value;
            }
        }
        
        /// <remarks/>
        public ErrorCode ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMobiles {
            get {
                return this.errorMobilesField;
            }
            set {
                this.errorMobilesField = value;
            }
        }
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitID {
            get {
                return this.submitIDField;
            }
            set {
                this.submitIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://HzTerrace.org/")]
    public enum ErrorCode {
        
        /// <remarks/>
        BALANCE_ERROR,
        
        /// <remarks/>
        BID_ERROR,
        
        /// <remarks/>
        CALLER_ERROR,
        
        /// <remarks/>
        MSG_LENGTH_ERROR,
        
        /// <remarks/>
        MSG_TYPE_ERROR,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        SEND_TIME_ERROR,
        
        /// <remarks/>
        SOURCE_ID_ERROR,
        
        /// <remarks/>
        SOURCE_ID_LENGTH_ERROR,
        
        /// <remarks/>
        SYSTEM_ERROR,
        
        /// <remarks/>
        USER_ID_OR_PWD_ERROR,
        
        /// <remarks/>
        PARAM_ERROR,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void MmsToServiceCompletedEventHandler(object sender, MmsToServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MmsToServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MmsToServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OpRespOfSendResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OpRespOfSendResp)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591